---
.travis.yml:
  rubygems_api_key: "CEXDzaf3MLvM/ZKSGcXiNyfZkDueLrYiH5Y4CeYlOiOdGnOr8CTmKBr2cc3VCMSxICI84dwpOCbrufX7NDPgwpSPxEsW0Rph8M3cdsqIm2pNSNzYwh7pg5FZZsMPTAr7eGRCgbCX1uUtdQ6Kwvi279eoTUuwe4P7akeFlU2M25Q="
